"""žinutė atminčiai_1

Revision ID: 2c0bb358e381
Revises: ab180c6a1971
Create Date: 2023-03-20 21:24:43.582473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0bb358e381'
down_revision = 'ab180c6a1971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_message_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_message_message'), ['message'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_message_message'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_message_email'), type_='unique')
        batch_op.alter_column('message',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
