"""Add one more column

Revision ID: de0c64c8ed97
Revises: 2c0bb358e381
Create Date: 2023-03-21 14:14:51.801885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0c64c8ed97'
down_revision = '2c0bb358e381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_more', sa.String(length=180), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_constraint('uq_message_message', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_message_one_more'), ['one_more'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_message_one_more'), type_='unique')
        batch_op.create_unique_constraint('uq_message_message', ['message'])
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('one_more')

    # ### end Alembic commands ###
